### ISSUE TITLE
Welcome Screen Frames

### ISSUE THREAD

**Issue by accuracy114** [maxheyn/TorghastTeams#5]
Currently, the welcome screen (default interface) shows/hide each font string individually. Find a way to group all the font string inside of one frame, so the function can just show/hide the one frame instead of doing show/hide on each font string.

---

Issues with grouping all font string in one frame:
1) sometimes font strings are null
2) when its not null, font strings are invisible or doesn't show up on the interface

**Comment by maxheyn** [comment]
Added a BodyContainer frame in 07d3b0341f787e9f60a05ec8196379660f22aa9e, all body texts are now included in it and can be hidden just by hiding the BodyContainer.

Planning on overhauling the appearance and phrasing of the body text in a future update, as well as adding a scrollbar or tabs so that the user can scroll/switch tabs when the information inevitably becomes more than can fit on the frame.
